name: Run Specs with Docker Compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build services
        run: cd spec && bin/build

      - name: Run services
        run: cd spec && docker compose up

      # - name: Check running containers
      #   run: docker ps -a
      # - name: Check logs
      #   run: docker logs backend

      - name: Run test suite
        run: cd spec && docker compose run --rm rspec bundle exec rspec features/
