# Run Specs with Docker Compose

name: Integration Tests

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build App image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.prep.outputs.tagged_image }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          push: false # do not push to docker registry (if we did, we would need to login first)

      - name: Build RSpec image
        uses: docker/build-push-action@v2
        with:
          context: ./spec
          file: spec/config/rspec.Dockerfile
          tags: ${{ steps.prep.outputs.tagged_image }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          push: false # do not push to docker registry (if we did, we would need to login first)

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # - name: Build services
      #   run: cd spec && docker buildx bake

      - name: Run services
        run: cd spec && docker compose up -d

      - name: Run test suite
        run: cd spec && docker compose run -T rspec bundle exec rspec --force-color features/
