# Run Specs with Docker Compose

name: Integration Tests

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          registry: docker.io
          service: rspec
          workdir: spec
          file: docker-compose.yml
          command: bin/ci-run-rspec-tests
